"""remove attendance

Revision ID: d1f03819d940
Revises: 221a03a18e77
Create Date: 2018-06-30 15:11:23.057008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1f03819d940'
down_revision = '221a03a18e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_Arrived', table_name='attendance')
    op.drop_index('ix_attendance_Start', table_name='attendance')
    op.drop_index('ix_attendance_class_id', table_name='attendance')
    op.drop_index('ix_attendance_session', table_name='attendance')
    op.drop_index('ix_attendance_student_id', table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('Arrived', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('session', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], [u'class.id'], name=u'attendance_class_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], [u'student.id'], name=u'attendance_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'attendance_pkey')
    )
    op.create_index('ix_attendance_student_id', 'attendance', ['student_id'], unique=False)
    op.create_index('ix_attendance_session', 'attendance', ['session'], unique=False)
    op.create_index('ix_attendance_class_id', 'attendance', ['class_id'], unique=False)
    op.create_index('ix_attendance_Start', 'attendance', ['Start'], unique=False)
    op.create_index('ix_attendance_Arrived', 'attendance', ['Arrived'], unique=False)
    # ### end Alembic commands ###
